export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_ROLES = 'FETCH_USER_ROLES';
export const FETCH_USER_STATUSES = 'FETCH_USER_STATUSES';
export const FETCH_USER_PROJECTS = 'FETCH_USER_PROJECTS';
export const FETCH_USER_PAYMENTS = 'FETCH_USER_PAYMENTS';
export const FETCH_USER_RAISES = 'FETCH_USER_RAISES';
export const FETCH_USER_WORKTIME = 'FETCH_USER_WORKTIME';
export const FETCH_USER_CALENDAR = 'FETCH_USER_CALENDAR';
export const FETCH_USER_PROJECT_DETAILS = 'FETCH_USER_PROJECT_DETAILS';

export const ADD_USER_WORKTIME = 'ADD_USER_WORKTIME';
export const ADD_USER = 'ADD_USER';

export const DELETE_USER_WORKTIME = 'DELETE_USER_WORKTIME';

export const EDIT_USER = 'EDIT_USER';

export const CLEAR_USERS = 'CLEAR_USER';
export const CLEAR_USER_SUB_STATE = 'CLEAR_USER_SUB_STATE';
