export const FETCH_WORKTIME = 'FETCH_WORKTIME';
export const FETCH_WORKTIME_ITEM = 'FETCH_WORKTIME_ITEM';
export const ADD_WORKTIME = 'ADD_WORKTIME';
export const EDIT_WORKTIME = 'EDIT_WORKTIME';
export const DELETE_WORKTIME = 'DELETE_WORKTIME';
export const CLEAR_WORKTIME = 'CLEAR_WORKTIME';
