export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENT = 'FETCH_CLIENT';
export const FETCH_CLIENT_FIELD_TYPES = 'FETCH_CLIENT_FIELD_TYPES';
export const FETCH_CLIENT_ORIGINS = 'FETCH_CLIENT_ORIGINS';
export const ADD_CLIENT = 'ADD_CLIENT';
