export const FETCH_PAYMENTS = 'FETCH_PAYMENTS';
export const FETCH_PAYMENT_STATUSES = 'FETCH_PAYMENT_STATUSES';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const CLEAN_UP_PAYMENTS = 'CLEAN_UP_PAYMENTS';
