export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT_STATUSES = 'FETCH_PROJECT_STATUSES';
export const ADD_PROJECT = 'ADD_PROJECT';
export const CLEAN_UP_PROJECTS = 'CLEAN_UP_PROJECTS';
