export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT_STATUSES = 'FETCH_PROJECT_STATUSES';
export const FETCH_PROJECT_ACCOUNTS = 'FETCH_PROJECT_ACCOUNTS';
export const FETCH_PROJECT_WORKTIME = 'FETCH_PROJECT_WORKTIME';
export const ADD_PROJECT = 'ADD_PROJECT';
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS';
